config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'equipe', to: 'static_pages#equipe'

  get 'cadastro', to: 'users#new'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'editar_cadastro', to: 'sessions#edit'
  post 'reset_password', to: 'sessions#update'
  post 'carrinho/adicionar/:id_produto', to: 'produtos#adicionar_ao_carrinho', as: 'carrinho_add'
  post 'carrinho/comprar/:id_produto', to: 'produtos#comprar', as: 'carrinho_comprar'
  delete 'carrinho/:id', to: 'carrinhos#destroy_item', as: 'carrinho_item'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :produtos, only: [:index, :show]
  resource :carrinho, only: [:show, :update]

  resources :enderecos, only: [:new, :create]
  resources :formas_pagamentos, only: [:new, :create]
  resources :ordems, only: [:new, :create, :show, :index]
end

app/models/carrinho.rb
# == Schema Information
#
# Table name: carrinhos
#
#  id         :bigint(8)        not null, primary key
#  ativo      :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)
#
# Indexes
#
#  index_carrinhos_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Carrinho < ApplicationRecord
  belongs_to :user
  has_many :carrinho_items, dependent: :destroy
end

app/controllers/carrinhos_controller.rb
# app/controllers/carrinhos_controller.rb
class CarrinhosController < ApplicationController
    # before_action :authenticate_user!
  
    def show
      @carrinho = current_user.current_carrinho
      @total_price = calculate_total_price(@carrinho)
    end

    def calculate_total_price(carrinho)
      carrinho.carrinho_items.includes(:produto).sum do |item|
        item.produto.preco * item.qtd
      end
    end
  
    def update
        @carrinho = current_user.current_carrinho
        carrinho_item = @carrinho.carrinho_items.find(params[:carrinho_item][:id])
    
        if carrinho_item.update(qtd: params[:carrinho_item][:qtd])
          redirect_to carrinho_path
           flash[:success] = 'Quantidade atualizada!'

        else
          redirect_to carrinho_path
        end
      end
    
    def destroy_item
      @carrinho = current_user.current_carrinho
      carrinho_item = @carrinho.carrinho_items.find(params[:id])
      carrinho_item.destroy
      respond_to do |format|
        format.js
      end
      flash[:success] = 'Item removido com sucesso!'

    end
  end
  

app/helpers/carrinhos_helper.rb
module CarrinhosHelper
end

app/views/carrinhos/show.html.erb
<div class="user-cart">
  <h1>Seu carrinho</h1>
  <div class="table-container">
    <table class='table table-striped table-hover table-green'>
      <thead>
        <tr>
          <th>Imagem</th>
          <th>Descrição</th>
          <th>Quantidade</th>
          <th>Preço</th>
          <th>Ações</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="table-body">
        <% @carrinho.carrinho_items.each do |item| %>
        <tr>
          <td><%= image_tag(item.produto.imagem) %></td>
          <td><%= item.produto.nome %></td>
          <td class="quantity-cell">
            <%= form_with model: item, url: carrinho_path(item), method: :patch, local: true do |f| %>
              <%= f.hidden_field :id %>
              <div class="quantity-controls">
                <button class="btn btn-outline-secondary decremento-btn" type="button">
                  <i class="fas fa-minus"></i>
                </button>
                <%= f.number_field :qtd, in: 1..99, class: "form-control quantidade-input" %>
                <button class="btn btn-outline-secondary incremento-btn" type="button">
                  <i class="fas fa-plus"></i>
                </button>
                <%= button_tag type: "submit", class: "btn btn-outline-secondary reload-btn" do %>
                  <i class="fas fa-sync-alt"></i>
                <% end %>
              </div>
             <% end %>
          </td>
          <td>R$ <%= number_to_currency(item.produto.preco * item.qtd) %></td>
          <td>
            <button type="button" class="btn btn-danger delete-item-btn" data-toggle="modal" data-target="#confirmationModal<%= item.id %>">
              <i class="fas fa-trash"></i>
            </button>
          </td>
        </tr>
        <div class="modal fade" id="confirmationModal<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel<%= item.id %>" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="confirmationModalLabel<%= item.id %>">Confirmar Exclusão</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja remover este item do carrinho?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary delete-confirm-btn" data-url="<%= carrinho_item_path(item) %>" data-item-id="<%= item.id %>">Sim</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="total-price-confirm">
    <h3>Total: R$ <%= number_to_currency(@total_price) %></h3>
    <%= link_to 'Finalizar Compra', new_ordem_path, class: 'btn btn-success' if @carrinho.carrinho_items.present? %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.delete-confirm-btn').click(function() {
      var url = $(this).data('url');

      $.ajax({
        type: 'DELETE',
        url: url,
        success: function(data) {
          location.reload();
        },
        error: function(xhr, status, error) {
          location.reload();
        }
      });
    });

    $(window).on('load', function() {
      $('html, body').animate({ scrollTop: 0 }, 'slow');
    });

    $('.incremento-btn').click(function() {
      var quantidadeInput = $(this).closest('.quantity-controls').find('.quantidade-input');
      quantidadeInput.val(parseInt(quantidadeInput.val()) + 1);
    });

    $('.decremento-btn').click(function() {
      var quantidadeInput = $(this).closest('.quantity-controls').find('.quantidade-input');
      var currentValue = parseInt(quantidadeInput.val());
      quantidadeInput.val(currentValue > 1 ? currentValue - 1 : 1);
    });
  });
</script>
<style>
  .quantity-cell {
    display: flex;
    align-items: center;
  }

  .quantity-controls {
    display: flex;
    align-items: center;
    height: 150px ;
  }

  .quantity-controls button {
    margin: 0;
  }

  .quantity-controls .quantidade-input {
    flex: 1;
    margin: 0 8px;
  }
</style>