config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'equipe', to: 'static_pages#equipe'

  get 'cadastro', to: 'users#new'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'editar_cadastro', to: 'sessions#edit'
  post 'reset_password', to: 'sessions#update'
  post 'carrinho/adicionar/:id_produto', to: 'produtos#adicionar_ao_carrinho', as: 'carrinho_add'
  post 'carrinho/comprar/:id_produto', to: 'produtos#comprar', as: 'carrinho_comprar'
  delete 'carrinho/:id', to: 'carrinhos#destroy_item', as: 'carrinho_item'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :produtos, only: [:index, :show]
  resource :carrinho, only: [:show, :update]

  resources :enderecos, only: [:new, :create]
  resources :formas_pagamentos, only: [:new, :create]
  resources :ordems, only: [:new, :create, :show, :index]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           default(""), not null
#  name            :string           not null
#  password_digest :string           default(""), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

  has_secure_password
  before_save :email_downcase

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }

  has_many :ordems
  has_one :carrinho, dependent: :destroy
  has_many :forma_pagamentos
  has_many :enderecos

  def update_password(new_password)
    self.password = new_password
    save
  end

  def current_carrinho
    carrinho || create_carrinho
  end

  private
    def email_downcase
      self.email.downcase!
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :require_logged_in_user, only: [:show]

  def new
    redirect_to root_path(current_user) if user_signed_in?
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = 'Cadastro realizado com sucesso'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = 'Dados atualizados com sucesso'
      redirect_to user_contacts_url(current_user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "Nome", class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: "Email", class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Senha", class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Repita sua senha", class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="new-user">
  <div class="acc-forms">
    <div class="form-label">
      <h1>Editar Perfil</h1>
    </div>

    <div class="form-inputs">
      <%= form_for current_user do |f| %>
        <%= render 'fields', f: f %>

        <%= f.submit 'Atualizar', class: 'btn btn-primary submit-button' %>
      <% end %>
    </div>
    <hr>
    <%= link_to 'Endereços', new_endereco_path%>
    <br>
    <%= link_to 'Forma de Pagamento', new_formas_pagamento_path %>
  </div>
</div>

app/views/users/new.html.erb
<div class="new-user">
  <div class="acc-forms">
    <div class="form-label">
      <%= image_tag 'user-solid.svg', size:"50x50" %>
      <h1>Cadastrar-se</h1>
    </div>

    <div class="form-inputs">
      <%= form_for @user do |f| %>
        <%= render 'fields', f: f %>

        <%= f.submit 'Cadastrar', class: 'btn btn-primary submit-button btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>