config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'equipe', to: 'static_pages#equipe'

  get 'cadastro', to: 'users#new'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'editar_cadastro', to: 'sessions#edit'
  post 'reset_password', to: 'sessions#update'
  post 'carrinho/adicionar/:id_produto', to: 'produtos#adicionar_ao_carrinho', as: 'carrinho_add'
  post 'carrinho/comprar/:id_produto', to: 'produtos#comprar', as: 'carrinho_comprar'
  delete 'carrinho/:id', to: 'carrinhos#destroy_item', as: 'carrinho_item'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :produtos, only: [:index, :show]
  resource :carrinho, only: [:show, :update]

  resources :enderecos, only: [:new, :create]
  resources :formas_pagamentos, only: [:new, :create]
  resources :ordems, only: [:new, :create, :show, :index]
end

app/models/produto.rb
# == Schema Information
#
# Table name: produtos
#
#  id           :bigint(8)        not null, primary key
#  ativo        :boolean          default(TRUE)
#  desconto     :decimal(, )      default(0.0)
#  fabricado_em :date
#  imagem       :string
#  nome         :string
#  origem       :string
#  preco        :decimal(, )
#  tipo         :string
#  validade     :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
require 'csv'
require 'open-uri'
class Produto < ApplicationRecord
    before_save :calcular_desconto, if: :preco_changed?

    scope :ativos, lambda {where(ativo: true)} 

    validates :nome, presence: true, uniqueness: true
    validates :imagem, presence: true, uniqueness: true

    def calcular_desconto
      if new_record? || desconto.nil?
        valor = (self.preco * rand(0.5..0.89)) + self.preco
        self.desconto = valor
      else
        self.desconto = valor if self.desconto.nil? 
      end
    end

    def self.criar_produtos_do_csv(file_path,tipo)
        if tipo == "csv"
            CSV.foreach(file_path, headers: true) do |row|
                Produto.create(
                  nome: row['nome'],
                  imagem: row['imagem'],
                  preco: row['preco'].to_f,
                  origem: row['origem'],
                  validade: Date.parse(row['validade']),
                  fabricado_em: Date.parse(row['fabricado_em']),
                  tipo: row['tipo']
                )
            end
        elsif tipo == "link"
            file_path = URI.open(file_path).read
            CSV.parse(file_path, headers: true) do |row|
                Produto.create(
                  nome: row['nome'],
                  imagem: row['imagem'],
                  preco: row['preco'].to_f,
                  origem: row['origem'],
                  validade: Date.parse(row['validade']),
                  fabricado_em: Date.parse(row['fabricado_em']),
                  tipo: row['tipo']
                )
            end
        end
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.ativos.sort
  end

  def show
    @produtos = Produto.find(params[:id])
  end

  def adicionar_ao_carrinho
    @produto = Produto.find(params[:id_produto])
    @carrinho = current_user.current_carrinho || current_user.create_current_carrinho

    item = @carrinho.carrinho_items.find_or_initialize_by(produto: @produto)
    item.qtd = (item.qtd || 0) + params[:quantidade].to_i
    item.save

    respond_to do |format|
      format.json { render json: { message: 'Produto adicionado ao carrinho com sucesso.' }, status: :ok }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/index.html.erb
<h3>Lista de Produtos</h3>
<div class="lista-container">
  <div class="produtos-container">
    <% if @produtos.present? %>
    <% @produtos.each do |produto| %>
      <% if produto.nome.present? %>
      <%= link_to produto_path(produto) do %>
        <div class="produtos-card">
          <div class="produtos-card-imagem">
             <%= image_tag(produto.imagem) %>
          </div>
          <hr class="produtos-card-divisor">

          <%end%>
          <div class="produtos-card-descricao">
          <p><small><del>R$ <%= number_to_currency(produto.desconto)%></del></small></p>
          <p class="mb-0"><h4><strong>R$ <%= number_to_currency(produto.preco) %></strong></h4></p>
          <p class="text-primary"><%= produto.nome %></p>
          <p class="text-secondary">Origem: <%= produto.origem %></p>
          <p class="text-secondary">Tipo: <%= produto.tipo %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <% else %>
      <div class="jumbotron" style="display: flex; flex-direction: column; align-items: flex-start;">
        <h1>Estoque Vasio</h1>
        <ul style="margin-top: 0;">Volte outra hora!</ul>
      </div>
    <% end %>
  </div>
</div>

app/views/produtos/show.html.erb
<div class="container">
  <%= link_to produtos_path, class: "text-decoration-none text-primary mb-3" do %>
    <i class="fas fa-arrow-left"></i> Voltar
  <% end %>

<div class="produto-card">
  <div class="produto-card-imagem">
    <%= image_tag(@produtos.imagem, class: "produto-card-imagem-tag") %>
  </div>
  <div class="produto-card-descricao">
    <h2><%= @produtos.nome %></h2>
          <p><small><del>R$ <%= number_to_currency(@produtos.desconto)%></del></small></p>
          <p class="mb-0"><h4><strong>R$ <%= number_to_currency(@produtos.preco) %></strong></h4></p>
          <p class="text-secondary">Origem: <%= @produtos.origem %></p>
          <p class="text-secondary">Data de Validade: <%= @produtos.validade.strftime('%d/%m/%Y') %></p>
          <p class="text-secondary">Data de Fabricação: <%= @produtos.fabricado_em.strftime('%d/%m/%Y') %></p>
          <p class="text-secondary">Tipo: <%= @produtos.tipo %></p>
    
    <hr>
    <div class="produto-card-botoes">
    <% if !user_signed_in? %>
      <%= link_to 'Entrar', entrar_path , class: 'btn btn-primary' %>

    <% else %>
      <div class="input-group mb-3">
        <input type="number" class="form-control quantidade-input" value="1" min="1">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary decremento-btn" type="button">-</button>
          <button class="btn btn-outline-secondary incremento-btn" type="button">+</button>
        </div>
      </div>  
      <button class="btn btn-warning btn-lg btn-block produto-adicionar" data-produto-id="<%= @produtos.id %>">Adicionar ao Carrinho</button>
      <%# <button class="btn btn-info btn-lg btn-block produto-comprar" data-produto-id="<%= @produtos.id %>
      <%# "> %>
        <%# Comprar</button> %>
    <% end %>
    </div>
  </div>
</div>
<script>
  $('.produto-adicionar').click(function() {
    var produtoId = $(this).data('produto-id');
    var quantidade = $('.quantidade-input').val();

    $('body').addClass('disable-clicks-loading');
    $(this).html('<i class="fas fa-spinner fa-spin"></i> Carregando...');
    $.ajax({
      type: 'POST',
      url: `/carrinho/adicionar/${produtoId}`,
      data: { quantidade: quantidade },
      success: function(data) {
        $.notify({icon: 'fas fa-info-circle', message: 'Adicionado ao carrinho com sucesso!'}, {type: 'success', z_index: 9999});
            setTimeout(function() {
              $('body').removeClass('disable-clicks-loading');
              window.location.href = "/produtos";
            }, 2000);
      },
      error: function(xhr, status, error) {
        $.notify({icon: 'fas fa-exclamation-triangle', message: "Erro ao adicionar no carrinho"}, {type: 'danger', z_index: 9999});
          setTimeout(function() {
              $('body').removeClass('disable-clicks-loading');
              window.location.href = "/produtos";
            }, 2000);
      }
    });
  });

  $('.produto-comprar').click(function() {
    var produtoId = $(this).data('produto-id');
    var quantidade = $('.quantidade-input').val();

    $.ajax({
      type: 'POST',
      url: `/carrinho/comprar/${produtoId}`,
      data: { quantidade: quantidade },
      success: function(data) {
      },
      error: function(xhr, status, error) {
      }
    });
  });

  $('.incremento-btn').click(function() {
  var quantidadeInput = $('.quantidade-input');
  quantidadeInput.val(parseInt(quantidadeInput.val()) + 1);
});

$('.decremento-btn').click(function() {
  var quantidadeInput = $('.quantidade-input');
  var currentValue = parseInt(quantidadeInput.val());
  quantidadeInput.val(currentValue > 1 ? currentValue - 1 : 1);
});
  </script>