config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'equipe', to: 'static_pages#equipe'

  get 'cadastro', to: 'users#new'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'editar_cadastro', to: 'sessions#edit'
  post 'reset_password', to: 'sessions#update'
  post 'carrinho/adicionar/:id_produto', to: 'produtos#adicionar_ao_carrinho', as: 'carrinho_add'
  post 'carrinho/comprar/:id_produto', to: 'produtos#comprar', as: 'carrinho_comprar'
  delete 'carrinho/:id', to: 'carrinhos#destroy_item', as: 'carrinho_item'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :produtos, only: [:index, :show]
  resource :carrinho, only: [:show, :update]

  resources :enderecos, only: [:new, :create]
  resources :formas_pagamentos, only: [:new, :create]
  resources :ordems, only: [:new, :create, :show, :index]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "© #{Time.now.year} Azeitanaro. Todos os direitos reservados.", root_path, class: "copyright" %>
  </small>

  <ul>
    <li><%= link_to 'Sobre', sobre_path, class: 'about' %></li>
    <li><%= link_to 'Equipe', equipe_path, class: 'team' %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="azeitanaro_navbar navbar navbar-static-top">
  <div class="container-fluid">

      <%= link_to root_url, class: "logo-empresa" do %> 

      <%= image_tag 'logo_fundo.svg', alt: "Logo da empresa", id: "navbar-logo" %>
      <span class="usuario-nome">Bem vindo<%=", " + current_user.name if user_signed_in? %></span>

      <% end %>
      
    <div class="navbar-header">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to produtos_path, title: "Loja", id: 'navbuttonh' do %><i class="fas fa-store fa-lg navbutton"> Loja</i><% end %></li>
        <li><%= link_to entrar_path, title: "Entrar", id: 'navbuttonh' do %><i class="fas fa-sign-in-alt fa-lg navbutton"> Entrar</i><% end  if !user_signed_in?%></li>
        <li>
          <%= link_to cadastro_path, title: "Nova Conta", id: 'navbuttonh' do %><i class="fas fa-user-plus fa-lg navbutton"> Cadastrar-se</i><% end if !user_signed_in?%>
        </li>
        <li><%= link_to ordems_path, title: "Pedidos", id: 'navbuttonh' do %><i class="fas fa-shopping-bag fa-lg navbutton"> Pedidos</i><% end  if user_signed_in?%></li>
        <li><%= link_to carrinho_path, title: "Carrinho", id: 'navbuttonh' do %><i class="fas fa-shopping-cart fa-lg navbutton"> Carrinho</i><% end if user_signed_in?%></li>
        <li><%= link_to edit_user_path(current_user), title: "Editar", id: 'navbuttonh' do %><i class="fas fa-edit fa-lg navbutton"> Editar</i><% end if user_signed_in?%></li>
        <li><%= link_to sair_path, method: :delete, title: "Sair", id: 'navbuttonh' do %><i class="fas fa-sign-out-alt fa-lg navbutton"> Sair</i><% end if user_signed_in?%></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Azeitanaro</title>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css">
  </head>
  <body data-route="<%= controller_path %>#<%= action_name %>">
   <%= render 'layouts/header' %>

   <div class="container">

     <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>

    <%= yield %>

   </div>
   
    <%= render 'layouts/info_loja'%>
    <%= render 'layouts/footer' %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"></script>
 </body>
</html>